version: "3.8"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/usr/share/grafana/dashboards
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
