{
 "title": "GitHub Server Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host_name", "label": "Host", "query": { "query": "label_values(host_name)" } }
  ]
 },
 "panels": [
  { "title": "Organizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Orgs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_orgs{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disabled Orgs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_disabled_orgs{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_orgs{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orgs by Host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_orgs{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Teams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_teams{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Team Members",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_team_members{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Teams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_orgs{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teams by Host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_teams{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_users{host_name=~\"$host_name\"}) - sum(total_suspended_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suspended Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_suspended_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_admin_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users by Host",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_users{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Repos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Repos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Repos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repos by Host",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Org Repos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_org_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Repos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_root_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fork Repos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_fork_repos{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pushes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_pushes{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pushes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 52 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_pushes{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Wikis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_wikis{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_issues{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_issues{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open vs Closed Issues",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_open_issues{host_name=~\"$host_name\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(total_closed_issues{host_name=~\"$host_name\"})",
     "legendFormat": "Closed"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_open_issues{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed Issues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_closed_issues{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issues by Host",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_issues{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pull Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Total Pull Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pull Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merged vs Unmerged PRs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_merged_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "Merged"
    },
    { "expr": "sum(total_mergeable_pulls)", "legendFormat": "Mergeable" },
    {
     "expr": "sum(total_unmergeable_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "Unmergeable"
    }
   ]
  },
  {
   "title": "Merged PRs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_merged_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mergeable PRs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 88 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_mergeable_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unmergeable PRs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_unmergeable_pulls{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Total Issue Comments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_issue_comments{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PR Comments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_pull_request_comments{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comments by Type and Host",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_issue_comments{host_name=~\"$host_name\"})",
     "legendFormat": "Issues ({{host_name}})"
    },
    {
     "expr": "sum by(host_name) (total_pull_request_comments{host_name=~\"$host_name\"})",
     "legendFormat": "PRs ({{host_name}})"
    },
    {
     "expr": "sum by(host_name) (total_commit_comments{host_name=~\"$host_name\"})",
     "legendFormat": "Commits ({{host_name}})"
    },
    {
     "expr": "sum by(host_name) (total_gist_comments{host_name=~\"$host_name\"})",
     "legendFormat": "Gists ({{host_name}})"
    }
   ]
  },
  {
   "title": "Total Commit Comments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_commit_comments{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gist Comments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_gist_comments{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Total Gists",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_gists{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gists",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 107 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_gists{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public vs Private Gists",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_gists{host_name=~\"$host_name\"})",
     "legendFormat": "Public"
    },
    { "expr": "sum(total_private_gists)", "legendFormat": "Private" }
   ]
  },
  { "title": "Hooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Total Hooks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_hooks{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs Inactive Hooks",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_active_hooks{host_name=~\"$host_name\"})",
     "legendFormat": "Active"
    },
    { "expr": "sum(total_inactive_hooks)", "legendFormat": "Inactive" }
   ]
  },
  {
   "title": "Active Hooks by Host",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (total_active_hooks{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Total Pages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_pages{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 129 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_pages{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Milestones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Total Milestones",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_milestones{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Milestones",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 138 },
   "targets": [
    {
     "expr": "sum by(host_name) (total_milestones{host_name=~\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open vs Closed Milestones",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_open_milestones{host_name=~\"$host_name\"})",
     "legendFormat": "Open"
    },
    { "expr": "sum(total_closed_milestones)", "legendFormat": "Closed" }
   ]
  }
 ]
}