---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: dashboards-config-volume
          mountPath: /usr/share/grafana/dashboards
        - name: provisioning-datasources-config-volume
          mountPath: /etc/grafana/provisioning/datasources
        - name: provisioning-dashboards-config-volume
          mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: dashboards-config-volume
          configMap:
            name: grafana-dashboards
        - name: provisioning-datasources-config-volume
          configMap:
            name: grafana-provisioning-datasources
        - name: provisioning-dashboards-config-volume
          configMap:
            name: grafana-provisioning-dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091

