name: Export Server Stats

on:
  workflow_dispatch:
  
  schedule:
  # runs 3x an hour, 17th, 32nd and 37th minute
    - cron:  '17/15 * * * *'
env:
  SERVER_STATS_DATA_FILE: server-stats-data.json

jobs:
  retrieve-server-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: bxtp4p/github-server-stats-prom-exporter-action/get-server-stats@refactoring
        id: get-server-stats
        with:
          personal-access-token: ${{ secrets.ACCESS_TOKEN }}
          enterprise-or-organization: ${{ secrets.ENTERPRISE_NAME }}
          filename: ${{ env.SERVER_STATS_DATA_FILE }}
          
      - name: Archive Server Stats data
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SERVER_STATS_DATA_FILE }}
          path: ${{ steps.get-server-stats.outputs.server-stats-data-file }}

  export-to-prometheus:
    needs: retrieve-server-stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.SERVER_STATS_DATA_FILE }}
          path: input/

      - uses: actions/checkout@v3

      - uses: bxtp4p/github-server-stats-prom-exporter-action/send-to-prometheus-gateway@refactoring
        id: send-to-prometheus-gateway
        with:
          server-stats-data-file:  input/${{ env.SERVER_STATS_DATA_FILE }}
          prometheus-pushgateway-url: ${{ secrets.PROMETHEUS_PUSHGATEWAY_URL }} 

      # - name: Show Prometheus Metrics
      #   run: echo "${{ steps.send-to-prometheus-gateway.outputs.prometheus-metrics }}"